/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/bYIxv6JAiXs
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { DropdownMenuTrigger, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"

export default function statements() {
  return (
    <div className="grid min-h-screen w-full lg:grid-cols-[400px_1fr]">
      <div className="border-r bg-gray-100/40 lg:block dark:bg-gray-800/40">
        <div className="flex h-full max-h-screen flex-col gap-2">
          <div className="flex h-[60px] items-center border-b px-6">
            <Link className="flex items-center gap-2 font-semibold" href="#">
              <LandmarkIcon className="h-6 w-6" />
              <span className="">Acme Inc</span>
            </Link>
            <Button className="ml-auto h-8 w-8" size="icon" variant="outline">
              <BellIcon className="h-4 w-4" />
              <span className="sr-only">Toggle notifications</span>
            </Button>
          </div>
          <div className="flex-1 overflow-auto py-2">
            <Card className="mx-4 my-6">
              <CardHeader>
                <CardTitle>Upload Document</CardTitle>
                <CardDescription>Upload a document to your financial dashboard.</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="grid w-full max-w-sm items-center gap-1.5">
                  <Label htmlFor="document">Document</Label>
                  <Input id="document" type="file" />
                </div>
              </CardContent>
            </Card>
            <Card className="mx-4 my-6">
              <CardHeader>
                <CardTitle>Financial Overview</CardTitle>
                <CardDescription>Key financial metrics for your company.</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-2 gap-4">
                  <div className="flex flex-col gap-2">
                    <span className="text-sm font-medium">Total Assets</span>
                    <span className="text-2xl font-bold">$2,200,000</span>
                  </div>
                  <div className="flex flex-col gap-2">
                    <span className="text-sm font-medium">Total Liabilities</span>
                    <span className="text-2xl font-bold">$1,100,000</span>
                  </div>
                  <div className="flex flex-col gap-2">
                    <span className="text-sm font-medium">Total Equity</span>
                    <span className="text-2xl font-bold">$1,100,000</span>
                  </div>
                  <div className="flex flex-col gap-2">
                    <span className="text-sm font-medium">Net Income</span>
                    <span className="text-2xl font-bold">$300,000</span>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
      <div className="flex flex-col">
        <header className="flex h-14 lg:h-[60px] items-center gap-4 border-b bg-gray-100/40 px-6 dark:bg-gray-800/40">
          <Link className="lg:hidden" href="#">
            <LandmarkIcon className="h-6 w-6" />
            <span className="sr-only">Home</span>
          </Link>
          <div className="w-full flex-1">
            <form>
              <div className="relative">
                <SearchIcon className="absolute left-2.5 top-2.5 h-4 w-4 text-gray-500 dark:text-gray-400" />
                <Input
                  className="w-full bg-white shadow-none appearance-none pl-8 md:w-2/3 lg:w-1/3 dark:bg-gray-950"
                  placeholder="Search"
                  type="search"
                />
              </div>
            </form>
          </div>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button
                className="rounded-full border border-gray-200 w-8 h-8 dark:border-gray-800 dark:border-gray-800"
                size="icon"
                variant="ghost"
              >
                <img
                  alt="Avatar"
                  className="rounded-full"
                  height="32"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "32/32",
                    objectFit: "cover",
                  }}
                  width="32"
                />
                <span className="sr-only">Toggle user menu</span>
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuLabel>My Account</DropdownMenuLabel>
              <DropdownMenuSeparator />
              <DropdownMenuItem>Settings</DropdownMenuItem>
              <DropdownMenuItem>Support</DropdownMenuItem>
              <DropdownMenuSeparator />
              <DropdownMenuItem>Logout</DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </header>
        <main className="flex flex-1 flex-col gap-4 p-4 md:gap-8 md:p-6">
          <div className="grid md:grid-cols-2 gap-6">
            <Card>
              <CardHeader>
                <CardTitle>Financial Overview</CardTitle>
                <CardDescription>Key financial metrics for your company.</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-2 gap-4">
                  <div className="flex flex-col gap-2">
                    <span className="text-sm font-medium">Total Assets</span>
                    <span className="text-2xl font-bold">$2,200,000</span>
                  </div>
                  <div className="flex flex-col gap-2">
                    <span className="text-sm font-medium">Total Liabilities</span>
                    <span className="text-2xl font-bold">$1,100,000</span>
                  </div>
                  <div className="flex flex-col gap-2">
                    <span className="text-sm font-medium">Total Equity</span>
                    <span className="text-2xl font-bold">$1,100,000</span>
                  </div>
                  <div className="flex flex-col gap-2">
                    <span className="text-sm font-medium">Net Income</span>
                    <span className="text-2xl font-bold">$300,000</span>
                  </div>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Financial Ratios</CardTitle>
                <CardDescription>Key financial ratios derived from your financial statements.</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="grid gap-4">
                  <div className="flex items-center justify-between">
                    <span>Current Ratio</span>
                    <span className="font-medium">1.5</span>
                  </div>
                  <div className="flex items-center justify-between">
                    <span>Debt-to-Equity Ratio</span>
                    <span className="font-medium">0.8</span>
                  </div>
                  <div className="flex items-center justify-between">
                    <span>Return on Assets</span>
                    <span className="font-medium">12%</span>
                  </div>
                  <div className="flex items-center justify-between">
                    <span>Inventory Turnover</span>
                    <span className="font-medium">3.2</span>
                  </div>
                  <div className="flex items-center justify-between">
                    <span>Accounts Receivable Turnover</span>
                    <span className="font-medium">6.5</span>
                  </div>
                  <div className="flex items-center justify-between">
                    <span>Debt-to-Assets Ratio</span>
                    <span className="font-medium">0.5</span>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
          <Card>
            <CardHeader>
              <CardTitle>Consolidated Financial Statements</CardTitle>
              <CardDescription>View your company's consolidated financial statements.</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid gap-4">
                <div className="grid gap-2">
                  <h3 className="font-semibold">Balance Sheet</h3>
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>Account</TableHead>
                        <TableHead>Amount</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      <TableRow>
                        <TableCell>Cash</TableCell>
                        <TableCell>$500,000</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>Accounts Receivable</TableCell>
                        <TableCell>$300,000</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>Inventory</TableCell>
                        <TableCell>$400,000</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>Total Current Assets</TableCell>
                        <TableCell>$1,200,000</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>Property, Plant & Equipment</TableCell>
                        <TableCell>$1,000,000</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>Total Assets</TableCell>
                        <TableCell>$2,200,000</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>Accounts Payable</TableCell>
                        <TableCell>$300,000</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>Accrued Expenses</TableCell>
                        <TableCell>$200,000</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>Total Current Liabilities</TableCell>
                        <TableCell>$500,000</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>Long-Term Debt</TableCell>
                        <TableCell>$600,000</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>Total Liabilities</TableCell>
                        <TableCell>$1,100,000</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>Retained Earnings</TableCell>
                        <TableCell>$800,000</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>Common Stock</TableCell>
                        <TableCell>$300,000</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>Total Equity</TableCell>
                        <TableCell>$1,100,000</TableCell>
                      </TableRow>
                    </TableBody>
                  </Table>
                </div>
                <div className="grid gap-2">
                  <h3 className="font-semibold">Income Statement</h3>
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>Account</TableHead>
                        <TableHead>Amount</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      <TableRow>
                        <TableCell>Revenue</TableCell>
                        <TableCell>$2,000,000</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>Cost of Goods Sold</TableCell>
                        <TableCell>$1,200,000</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>Gross Profit</TableCell>
                        <TableCell>$800,000</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>Operating Expenses</TableCell>
                        <TableCell>$400,000</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>Operating Income</TableCell>
                        <TableCell>$400,000</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>Interest Expense</TableCell>
                        <TableCell>$50,000</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>Income Before Taxes</TableCell>
                        <TableCell>$350,000</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>Income Taxes</TableCell>
                        <TableCell>$50,000</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>Net Income</TableCell>
                        <TableCell>$300,000</TableCell>
                      </TableRow>
                    </TableBody>
                  </Table>
                </div>
                <div className="grid gap-2">
                  <h3 className="font-semibold">Cash Flow Statement</h3>
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>Account</TableHead>
                        <TableHead>Amount</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      <TableRow>
                        <TableCell>Net Income</TableCell>
                        <TableCell>$300,000</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>Depreciation and Amortization</TableCell>
                        <TableCell>$100,000</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>Decrease in Accounts Receivable</TableCell>
                        <TableCell>$50,000</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>Increase in Inventory</TableCell>
                        <TableCell>($50,000)</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>Increase in Accounts Payable</TableCell>
                        <TableCell>$100,000</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>Net Cash Provided by Operating Activities</TableCell>
                        <TableCell>$500,000</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>Purchase of Property, Plant and Equipment</TableCell>
                        <TableCell>($200,000)</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>Net Cash Used in Investing Activities</TableCell>
                        <TableCell>($200,000)</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>Proceeds from Long-Term Debt</TableCell>
                        <TableCell>$200,000</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>Repayment of Long-Term Debt</TableCell>
                        <TableCell>($100,000)</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>Net Cash Provided by Financing Activities</TableCell>
                        <TableCell>$100,000</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>Net Increase in Cash</TableCell>
                        <TableCell>$400,000</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>Cash at Beginning of Year</TableCell>
                        <TableCell>$100,000</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>Cash at End of Year</TableCell>
                        <TableCell>$500,000</TableCell>
                      </TableRow>
                    </TableBody>
                  </Table>
                </div>
              </div>
            </CardContent>
          </Card>
        </main>
      </div>
    </div>
  )
}

function BellIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9" />
      <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0" />
    </svg>
  )
}


function LandmarkIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="3" x2="21" y1="22" y2="22" />
      <line x1="6" x2="6" y1="18" y2="11" />
      <line x1="10" x2="10" y1="18" y2="11" />
      <line x1="14" x2="14" y1="18" y2="11" />
      <line x1="18" x2="18" y1="18" y2="11" />
      <polygon points="12 2 20 7 4 7" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}
